### ISSUE TITLE
--api-key option missing from help doc

### ISSUE THREAD

**Issue by dylanjw** [handshake-org/hs-client#22]
Maybe this is obvious to people familiar with handshake, but as a new user I would like to have all command line options to the tool im using be easily found rather than inferring command line options from other related tools:

```

$ ./bin/hsw-cli account list      
Error: Unauthorized (bad API key).
    at WalletClient.request (/home/dwilson/code/hs-client/node_modules/bcurl/lib/client.js:201:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)

$ ./bin/hsw-cli --api-key bikeshed account list
[
  "default",
]
```

No mention of `--api-key` in the help output:
```
$ ./bin/hsw-cli                                
Unrecognized command.
Commands:
  $ listen: Listen for events.
  $ get: View wallet.
  $ master: View wallet master key.
  $ shared add [xpubkey]: Add key to wallet.
  $ shared remove [xpubkey]: Remove key from wallet.
  $ balance: Get wallet balance.
  $ history: View TX history.
  $ pending: View pending TXs.
  $ coins: View wallet coins.
  $ account list: List account names.
  $ account create [account-name]: Create account.
  $ account get [account-name]: Get account details.
  $ address: Derive new address.
  $ change: Derive new change address.
  $ retoken: Create new api key.
  $ send [address] [value]: Send transaction.
  $ mktx [address] [value]: Create transaction.
  $ sign [tx-hex]: Sign transaction.
  $ zap [age?]: Zap pending wallet TXs.
  $ tx [hash]: View transaction details.
  $ blocks: List wallet blocks.
  $ block [height]: View wallet block.
  $ view [tx-hex]: Parse and view transaction.
  $ import [wif|hex]: Import private or public key.
  $ watch [address]: Import an address.
  $ key [address]: Get wallet key by address.
  $ dump [address]: Get wallet key WIF by address.
  $ lock: Lock wallet.
  $ unlock [passphrase] [timeout?]: Unlock wallet.
  $ resend: Resend pending transactions.
  $ rescan [height]: Rescan for transactions.
Other Options:
  --passphrase [passphrase]: For signing/account-creation.
  --account [account-name]: Account name.
```

**Comment by pinheadmz** [comment]
Thanks @dylanjw ! We could add that to the help menu. All the commands take various parameters though. Take a look at the official API docs:

https://handshake-org.github.io/api-docs/

api-keys are discussed there as well as other options. I'm working today on documenting all the new features that have been added to hsd recently.

There's also additional configuration options for the full node and client here:

https://handshake-org.github.io/guides/config.html

**Comment by bemusementpark** [comment]
Maybe there could be a 1-liner...

```
$ ./bin/hsw-cli                                
Unrecognized command.
Commands:
```

could instead be

```
$ ./bin/hsw-cli                                
for full params see: https://handshake-org.github.io/api-docs/
Commands:
```

or

```
$ ./bin/hsw-cli                                
=== handshake wallet CLI ===
common params include:
api-key lorem ipsum dolor sit amet
Commands:
```

**Comment by dylanjw** [comment]
Complex command line utilities with many sub commands with their own options often have a "help" option on subcommands which allows nesting the help document, keeping the top level help pretty simple.  For example look at npm:

```
$  npm

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview
[...]

$  npm create -h                                                                                                       

npm init [--force|-f|--yes|-y|--scope]
npm init <@scope> (same as `npx <@scope>/create`)
npm init [<@scope>/]<name> (same as `npx [<@scope>/]create-<name>`)

aliases: create, innit
$
```

**Comment by pinheadmz** [comment]
Anyone in this thread interested in opening a pull request to make the help menu more clear?

**Comment by pinheadmz** [comment]
@rdsoze thanks you are correct. This issue was closed by https://github.com/handshake-org/hs-client/pull/35
